apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-qccu
  namespace: rh-ee-dchouras-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:c3ece14f25d344992bfc430d6aeca2a56339e8b84328bf61d64c137b531bc655
        name: my-nodejs
        resources: {}
status: {}
